[build]
  publish = "dist/"
  command = "npm run build"
  
  [[redirects]]
    # Rewrite all requests that 404 to /, to support SPA history
    from = "/*"
    to = "/"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "frame-ancestors 'none'"
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = 'GET, POST, PATCH, PUT, DELETE, OPTIONS'
        Access-Control-Allow-Headers = 'Origin, Content-Type, X-Auth-Token'

[[headers]]
    for = "/*.wasm"
    [headers.values]
        Content-Type = "application/wasm"